=== VeronikaAlifer/BookDBTAT/resourses/Library_Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/library_schema" xmlns:tns="http://www.example.org/library_schema"
	elementFormDefault="qualified">

	<xs:complexType name="item">
		<xs:sequence>
			<xs:element name="title" type="xs:string" />
			<xs:element name="pages" type="xs:int" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="bookstore">
		<xs:complexType>
			<xs:sequence>

				<xs:element name="books">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="book" type="tns:item" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="newspapers">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="newspaper" type="tns:item" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="magazines">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="magazine" type="tns:item" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== VeronikaAlifer/BookDBTAT/resourses/LibraryFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<bookstore xmlns="http://www.example.org/library_schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/library_schema Library_Schema.xsd">
	
	<books>
		<book>
			<title>Everyday Italian</title>
			<pages>123</pages>
		</book>
		<book>
			<title>Harry Potter</title>
			<pages>456</pages>
		</book>
	</books>
	
	<newspapers>
		<newspaper>
			<title>The Times</title>
			<pages>13</pages>
		</newspaper>
		<newspaper>
			<title>Daily Express</title>
			<pages>23</pages>
		</newspaper>
	</newspapers>
	
	<magazines>
		<magazine>
			<title>Vogue</title>
			<pages>245</pages>
		</magazine>
		<magazine>
			<title>Cosmopolitan</title>
			<pages>256</pages>
		</magazine>
	</magazines>

</bookstore>
